name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: 59 23 * * *

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kry9ton/image:latest && docker push kry9ton/image:latest
